name: ghost
version: 2.0.2
description: Ghost CMS API client that closely follows the official implementation
homepage: https://github.com/0xVesion/dart_ghost

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  http: ^0.13.5
  json_annotation: ^4.7.0

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.1
  json_serializable: ^6.5.4