name: ghost
version: 2.0.3
description: Ghost CMS API client that closely follows the official implementation
homepage: https://github.com/0xVesion/dart_ghost

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  http: ^1.0.0
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.9
  flutter_lints: ^2.0.2
  json_serializable: ^6.7.1
