name: ghost
version: 1.0.2
description: Ghost CMS API client that closely follows the official implementation
homepage: https://github.com/0xVesion/dart_ghost

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  http: ^0.12.2
  json_annotation: ^3.1.1

dev_dependencies:
  pedantic: ^1.9.0
  json_serializable: ^3.5.1
  build_runner: ^1.10.13