name: ghost
version: 2.0.1
description: Ghost CMS API client that closely follows the official implementation
homepage: https://github.com/0xVesion/dart_ghost

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  http: ^0.13.4
  json_annotation: ^4.5.0

dev_dependencies:
  build_runner: ^2.1.11
  flutter_lints: ^2.0.1
  json_serializable: ^6.2.0